# Generated by Django 5.2.1 on 2025-05-19 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', '创建用户'), ('user_updated', '更新用户'), ('user_deleted', '删除用户'), ('user_activated', '启用用户'), ('user_deactivated', '禁用用户'), ('role_changed', '角色变更'), ('password_reset', '密码重置'), ('user_login', '用户登录'), ('user_logout', '用户登出'), ('user_login_failed', '登录失败'), ('project_created', '创建项目'), ('project_updated', '更新项目'), ('project_deleted', '删除项目')], max_length=50, verbose_name='操作类型')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('details', models.TextField(verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='目标类型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='admin_panel_user_id_9a5ec1_idx'), models.Index(fields=['action'], name='admin_panel_action_d5e0a0_idx'), models.Index(fields=['timestamp'], name='admin_panel_timesta_4c3bd5_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='admin_panel_target__3bf13d_idx')],
            },
        ),
    ]
