# Generated by Django 5.2.1 on 2025-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', '创建用户'), ('user_updated', '更新用户'), ('user_deleted', '删除用户'), ('user_activated', '启用用户'), ('user_deactivated', '禁用用户'), ('role_changed', '角色变更'), ('password_reset', '密码重置'), ('user_login', '用户登录'), ('user_logout', '用户登出'), ('user_login_failed', '登录失败'), ('project_created', '创建项目'), ('project_updated', '更新项目'), ('project_deleted', '删除项目'), ('device_created', '创建设备'), ('device_updated', '更新设备'), ('device_deleted', '删除设备'), ('device_key_reset', '重置设备密钥'), ('device_command_sent', '发送设备命令'), ('sensor_created', '创建传感器'), ('sensor_updated', '更新传感器'), ('sensor_deleted', '删除传感器'), ('actuator_created', '创建执行器'), ('actuator_updated', '更新执行器'), ('actuator_deleted', '删除执行器'), ('actuator_controlled', '控制执行器'), ('strategy_created', '创建策略'), ('strategy_updated', '更新策略'), ('strategy_deleted', '删除策略'), ('strategy_enabled', '启用策略'), ('strategy_disabled', '禁用策略'), ('strategy_executed', '执行策略'), ('system_configured', '系统配置'), ('backup_created', '创建备份'), ('backup_restored', '恢复备份'), ('api_accessed', 'API访问'), ('file_uploaded', '文件上传'), ('file_downloaded', '文件下载')], max_length=50, verbose_name='操作类型'),
        ),
    ]
