# Generated by Django 5.2.1 on 2025-05-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='例如：DEV-YYYYYY', max_length=20, unique=True, verbose_name='设备号')),
                ('device_identifier', models.CharField(help_text='可以是MAC地址、序列号等', max_length=100, unique=True, verbose_name='设备标识')),
                ('device_key', models.CharField(blank=True, help_text='用于设备认证', max_length=64, verbose_name='设备密钥')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unregistered', '未注册')], default='unregistered', max_length=20, verbose_name='设备状态')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='执行器名称')),
                ('actuator_type', models.CharField(help_text='例如：switch, dimmer', max_length=50, verbose_name='执行器类型')),
                ('command_key', models.CharField(help_text='用于向设备发送命令的标识', max_length=50, verbose_name='命令键名')),
                ('current_state', models.CharField(blank=True, help_text='例如：ON, OFF, 50%', max_length=20, null=True, verbose_name='当前状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='iot_devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '执行器',
                'verbose_name_plural': '执行器',
                'ordering': ['device', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(help_text='例如：PRJ-XXXXXX', max_length=20, unique=True, verbose_name='项目号')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iot_devices.project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='传感器名称')),
                ('sensor_type', models.CharField(help_text='例如：temperature, humidity', max_length=50, verbose_name='传感器类型')),
                ('unit', models.CharField(blank=True, help_text='例如：°C, %', max_length=20, null=True, verbose_name='单位')),
                ('value_key', models.CharField(help_text='用于从设备消息中提取该传感器值的键名', max_length=50, verbose_name='值键名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='iot_devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '传感器',
                'verbose_name_plural': '传感器',
                'ordering': ['device', 'name'],
            },
        ),
    ]
