# Generated by Django 5.2.1 on 2025-05-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='浮点值')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='字符串值')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iot_devices.sensor')),
            ],
            options={
                'verbose_name': '传感器数据',
                'verbose_name_plural': '传感器数据',
                'ordering': ['-timestamp'],
            },
        ),
    ]
