# Generated by Django 5.2.1 on 2025-05-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0002_actuator_description_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='description',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='iot_devices.sensor', verbose_name='传感器'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='浮点数值'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='字符串值'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor', '-timestamp'], name='iot_devices_sensor__d4a020_idx'),
        ),
    ]
