# Generated by Django 5.2.1 on 2025-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0003_remove_actuator_description_alter_sensordata_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='modbus_address',
            field=models.IntegerField(blank=True, null=True, verbose_name='寄存器地址'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='modbus_data_type',
            field=models.CharField(blank=True, help_text='例如：int16, uint16, boolean', max_length=20, null=True, verbose_name='数据类型'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='modbus_register_type',
            field=models.CharField(blank=True, help_text='例如：holding_register, coil', max_length=20, null=True, verbose_name='寄存器类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='modbus_ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Modbus IP地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='modbus_port',
            field=models.IntegerField(blank=True, default=502, null=True, verbose_name='Modbus 端口'),
        ),
        migrations.AddField(
            model_name='device',
            name='modbus_slave_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Modbus 从站ID'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol_type',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('tcp', 'TCP原生'), ('modbus_tcp', 'Modbus TCP')], default='mqtt', max_length=20, verbose_name='通信协议'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='modbus_address',
            field=models.IntegerField(blank=True, null=True, verbose_name='寄存器地址'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='modbus_count',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='寄存器数量'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='modbus_data_type',
            field=models.CharField(blank=True, help_text='例如：int16, uint16, float32, boolean', max_length=20, null=True, verbose_name='数据类型'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='modbus_register_type',
            field=models.CharField(blank=True, help_text='例如：holding_register, input_register, coil, discrete_input', max_length=20, null=True, verbose_name='寄存器类型'),
        ),
    ]
