# Generated by Django 5.2.1 on 2025-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0004_actuator_modbus_address_actuator_modbus_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='modbus_address',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='modbus_data_type',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='modbus_register_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='modbus_ip_address',
        ),
        migrations.RemoveField(
            model_name='device',
            name='modbus_port',
        ),
        migrations.RemoveField(
            model_name='device',
            name='modbus_slave_id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='modbus_address',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='modbus_count',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='modbus_data_type',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='modbus_register_type',
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol_type',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('tcp', 'TCP原生')], default='mqtt', max_length=20, verbose_name='通信协议'),
        ),
    ]
