# Generated by Django 5.2.1 on 2025-05-17 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0005_remove_modbus_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('command_value', models.CharField(max_length=100, verbose_name='命令值')),
                ('result', models.BooleanField(default=True, verbose_name='执行结果')),
                ('response', models.TextField(blank=True, null=True, verbose_name='响应消息')),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_history', to='iot_devices.actuator', verbose_name='执行器')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '执行器命令',
                'verbose_name_plural': '执行器命令',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actuator', '-timestamp'], name='iot_devices_actuato_a64af6_idx')],
            },
        ),
    ]
