# Generated by Django 5.2.1 on 2025-05-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0006_actuatorcommand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuatorcommand',
            old_name='response',
            new_name='response_message',
        ),
        migrations.RemoveField(
            model_name='actuatorcommand',
            name='result',
        ),
        migrations.RemoveField(
            model_name='actuatorcommand',
            name='sender',
        ),
        migrations.AddField(
            model_name='actuatorcommand',
            name='response_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='响应时间'),
        ),
        migrations.AddField(
            model_name='actuatorcommand',
            name='source',
            field=models.CharField(choices=[('user', '用户操作'), ('strategy', '策略触发'), ('system', '系统操作')], default='user', max_length=20, verbose_name='命令来源'),
        ),
        migrations.AddField(
            model_name='actuatorcommand',
            name='source_detail',
            field=models.CharField(blank=True, help_text='例如：策略名称、用户名等', max_length=100, null=True, verbose_name='来源详情'),
        ),
        migrations.AddField(
            model_name='actuatorcommand',
            name='status',
            field=models.CharField(choices=[('pending', '待响应'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='pending', max_length=20, verbose_name='命令状态'),
        ),
        migrations.AlterField(
            model_name='actuatorcommand',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='iot_devices.actuator', verbose_name='执行器'),
        ),
        migrations.AlterField(
            model_name='actuatorcommand',
            name='command_value',
            field=models.CharField(help_text='发送的命令值', max_length=100, verbose_name='命令值'),
        ),
        migrations.CreateModel(
            name='ActuatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('value', models.CharField(help_text='执行器上报的状态值', max_length=100, verbose_name='状态值')),
                ('source', models.CharField(default='device', help_text='数据来源，例如：device, system', max_length=50, verbose_name='数据来源')),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='iot_devices.actuator', verbose_name='执行器')),
            ],
            options={
                'verbose_name': '执行器数据',
                'verbose_name_plural': '执行器数据',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actuator', '-timestamp'], name='iot_devices_actuato_9d8111_idx')],
            },
        ),
    ]
